Update base
ti-spring/spring-crib-notes pull request #1
Opened 2022-10-06 05:09 UTC by hiji

## 概要

## レビュー依頼前のチェックリスト

- [ ] 作業時間を記録していること
- [ ] セルフレビュー済みであること
- [ ] PRに適切なtarget branchを設定済みであること

ソースコード特有の項目

- [ ] 理解しづらいコードはコメントで補足説明済みであること
- [ ] `./mvn clean verify`を実行して結果が`BUILD SUCCESS`であること

## 動作確認方法

- [ ] 生成したHTMLの表示が崩れていないこと

## レビューアに確認して欲しいポイント

- ドキュメントの修正
  - このドキュメントについて　〜　Webアプリ開発ノウハウの入力チェックまで
- コードの修正
  - 依存ライブラリのバージョンアップ

## レビューアへの申し送り事項

- ドキュメント中のリンクだけは、内容を見直していないドキュメント含めて一通り修正しています
- Spring Cloudのバージョンの妥当性について
  - Spring Initilizrで生成したら`2021.0.4`が使われていることを確認しました
  - （今回は Sping Cloud Stream を依存に指定して生成しました）
- Bean Validationのメッセージを`messages.properties`に指定した場合のパラメータ指定方法について
  - `@Length`の`{max}`の代わりに`{0}`や`{1}`を試したところ、`{0}`は`name`という文字列がバインドされ、`{1}`は`{1}`のままでした
  - 結果からはパラメータ解決をHibernate側でしているので、`messages.properties`に定義してもルールはHibernateに合わせないといけなさそうです
- ローカル検証用に、Sphinxビルド＆textlint用に使える`Dockerfile`を作成しています  
  - イメージをビルドする（名前は何でも）
    - 例：`docker build . -t spring-crib-notes-build`
  - HTMLを生成する場合
    - リポジトリのディレクトリを`/repos`にマウントして、コンテナ起動する
      - 例：`docker run --rm  -v ~/work/tis/ti-spring/spring-crib-notes:/repos spring-crib-notes-build`
    - `doc/_build/html`にHTMLが出力されている
  - textlintを実行する場合
    - `doc`配下で`npm install` しておく
    - リポジトリのディレクトリを`/repos`にマウントして、`npx textlint [ディレクトリ | ファイル]`を引数にして、コンテナを起動する
      - 例：`docker run --rm  -v ~/work/tis/ti-spring/spring-crib-notes:/repos spring-crib-notes-build npx textlint web`
 
## その他、気になること

- `mvnw`を用意した方がよさそうには思いましたが、まだ何もしていないです

---

## レビュー後、マージ前のチェックリスト（レビューア用のチェックリスト）

- [ ] レビュー時間を記録していること
- [ ] PRに適切なtarget branchを設定済みであること

---

| 作業分類             |時間(h)|
|------------------|---|
| 実装・執筆            |45|
| レビュー(backpaper0) |0|

2022-10-07 07:50 UTC, backpaper0 requested changes

2022-10-07 07:50 UTC, backpaper0 commented on doc/common/database/doma2.rst
>    使用するデータベースをDoma2に認識させるための設定を追加します。
doma-spring-boot 1.5.0からSLF4Jのロガーが追加されたので、`doma.jdbc-logger=SLF4J`も設定しておいた方が嬉しいかもしれません。

参考

- https://github.com/domaframework/doma-spring-boot/releases/tag/1.5.0
- https://github.com/domaframework/doma-spring-boot#properties-file-configuration

2022-10-07 07:50 UTC, backpaper0 commented on doc/common/database/sql-management.rst
>  * `Flyway Documentation - Maven Plugin <https://flywaydb.org/documentation/maven/>`_
リダイレクトされますが、URLが以下に変わったようです。

- https://flywaydb.org/documentation/usage/maven/

2022-10-07 07:50 UTC, backpaper0 commented on doc/common/database/sql-management.rst
>  Flyway Maven Plugin / SQL Maven Plugin の設定例
`properties-maven-plugin`は`1.1.0`がリリースされているみたいなので、可能ならバージョンアップしたいです。

2022-10-07 07:50 UTC, backpaper0 commented on doc/common/database/sql-management.rst
>  Flyway Maven Plugin / SQL Maven Plugin の設定例
`flyway-maven-plugin`も新しいバージョンが出ていますね。

2022-10-07 07:50 UTC, backpaper0 commented on doc/web/static-resource-cache/index.rst
> +  * :spring-boot-doc:`Common Application Properties <reference/html/application-properties>`
ビルド済みドキュメントでリンクをクリックするとURL末尾に`.html`がなくて404になりました。

2022-10-07 07:50 UTC, backpaper0 commented on doc/web/validation/database-validation.rst
> +  例えばバリデーションで重複登録のチェックを行ったとしても、同時に登録処理が行われてしまうとバリデーションのタイミングでエラーにならないというようなこともありえます。バリデーションだけでデータの不整合を確実に防げるわけではありませんので、データベースの制約を使用する等、データの不整合が発生しないよう十分に注意してください。
> 同時に登録処理が行われてしまうと

「同時に**複数の**登録処理が行われてしまうと」とした方が意味が通じやすそうだと思いました。

2022-10-07 08:54 UTC, hiji commented on doc/web/validation/database-validation.rst
> +  例えばバリデーションで重複登録のチェックを行ったとしても、同時に登録処理が行われてしまうとバリデーションのタイミングでエラーにならないというようなこともありえます。バリデーションだけでデータの不整合を確実に防げるわけではありませんので、データベースの制約を使用する等、データの不整合が発生しないよう十分に注意してください。
対応しました。

436d8219b500f2ad6da01a466ef6d6c0c5fc7b34

2022-10-07 08:57 UTC, hiji commented on doc/web/static-resource-cache/index.rst
> +  * :spring-boot-doc:`Common Application Properties <reference/html/application-properties>`
すみません、気づいていませんでした。ここはまだ文章見直し前でしたが、リンク先を Common Properties から Web Properties に変更した方がよさそうに思えたので、周辺の文章も見直しました。

faa0ee79e377590be51d51ac4a0aec7786cddb26

2022-10-07 08:59 UTC, hiji commented on doc/common/database/sql-management.rst
>  Flyway Maven Plugin / SQL Maven Plugin の設定例
Maven Pluginのバージョンアップは失念していました...
バージョンアップのため設定を見直すと、H2が古いバージョンを使っていたのも発覚したので、合わせて修正しました。（同じミスが発生しづらいようバージョンはSpring側のプロパティを使いました）

5aea7d6cac6a7c18599985d526a8eed128d16480

2022-10-07 09:00 UTC, hiji commented on doc/common/database/sql-management.rst
>  * `Flyway Documentation - Maven Plugin <https://flywaydb.org/documentation/maven/>`_
すみません、リダイレクトされているのに気づいていませんでした。修正しました。

bb6dd8409fe8371ebbc7473eee18d19c8e6cfdcc

2022-10-07 09:01 UTC, hiji commented on doc/common/database/doma2.rst
>    使用するデータベースをDoma2に認識させるための設定を追加します。
その機能に気づいていませんでした。プロパティと一緒に依存関係も必要でしたので、合わせて対応しました。

9ef949044997dec3af182f8ccf8f5d4b21f71ca5

2022-10-07 10:54 UTC, backpaper0 commented on doc/common/database/sql-management.rst
>  * `Flyway Documentation - Maven Plugin <https://flywaydb.org/documentation/maven/>`_
元からの文章だと思いますが以下も対応をお願いします！

```
Flywayのその他のコマンドや、 アプリケーションの起動時ではなく任意のタイミングでFlywayのMigrateコマンドを実行したい場合は、`FlywayのMaven Plugin <https://flywaydb.org/documentation/maven/>`_\ を使用する事で実行が可能です。
```

2022-10-07 10:58 UTC, backpaper0 commented on doc/web/static-resource-cache/index.rst
> +  * :spring-boot-doc:`Common Application Properties <reference/html/application-properties>`
修正して頂きましたが、リンク先が`htmlsingle`になっていますね。
`application-properties.html`の方が良いと思います。

2022-10-07 11:06 UTC, hiji commented on doc/web/static-resource-cache/index.rst
> +  * :spring-boot-doc:`Common Application Properties <reference/html/application-properties>`
すみません、修正しました。

d29e5ee85961bad0edfae9cc2171b1405cfa4a8d

2022-10-07 11:06 UTC, hiji commented on doc/common/database/sql-management.rst
>  * `Flyway Documentation - Maven Plugin <https://flywaydb.org/documentation/maven/>`_
すみません、修正しました。

68b153bc384bd736a6dcc6fa204f17463eb60230

2022-10-11 00:55 UTC, backpaper0 requested changes

2022-10-11 00:55 UTC, backpaper0 commented on samples/pom.xml
>      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
既存部分へのコメントになりますが、`project.build.sourceEncoding`と`project.reporting.outputEncoding`は不要だと思います。
今のSpring Initializrでプロジェクトを作成してもこれらは書かれていません。

これらを削除する前後で`mvn help:effective-pom -Doutput=effective-pom.xml`で出力した`effective-pom.xml`の内容に変化がなければ削除しちゃってください。

2022-10-11 00:55 UTC, backpaper0 commented on samples/common/doma2/src/main/java/keel/User.java
> +@Entity(immutable = true)
あえてイミュータブルにしなくても良いと思いましたが、イミュータブルにした方が良い理由はありますか？（個人的にはイミュータブルの方が好きですが、この施策としてどうしてもイミュータブルにしなければというほどではないです）

2022-10-11 00:55 UTC, backpaper0 commented on samples/batch/doma2-spring-batch/pom.xml
> +    <relativePath>../../pom.xml</relativePath>
単なる確認ですが、`pom.xml`を明記した理由を教えてもらっていいですか？

2022-10-11 00:55 UTC, backpaper0 commented on samples/api/api-error-handling/pom.xml
こちらにも`doma-slf4j`を追加してほしいです。

以下の`pom.xml`も同様です。

- samples/aws/rds/pom.xml
- samples/batch/doma2-spring-batch/pom.xml
- samples/web/doma2-optimistic-lock/pom.xml
- samples/web/double-submission/pom.xml
- samples/web/error-handling/pom.xml
- samples/web/table-authentication/pom.xml
- samples/web/validation/pom.xml

2022-10-11 00:55 UTC, backpaper0 commented on samples/api/api-error-handling/src/test/resources/datasets/users.yml
> +ROLES:
単なる確認ですが、テーブル名とカラム名をupper caseにしているのは何故でしょうか？

元のCSVがlower caseだったので気になりました。

2022-10-11 02:02 UTC, hiji commented on samples/api/api-error-handling/src/test/resources/datasets/users.yml
> +ROLES:
`doma2-optimistic-lock`の方はDDLでも大文字を使っていて、そちらを先に実装していたので、コピペしたときに大文字のままになってしまっていました。

改めてSQL周りを見直したのですが、DDLの方でも大文字小文字が混在していたり、古いデータ型の`SERIAL`を使っていることがわかったので、全体的に小文字で統一するように修正しました。
（H2ではデフォルトだと全て大文字に変換されるようなのですが、小文字の方が明らかに多かったので修正量を考えて小文字に統一しました）

44ccf3a36d199f4ce96058a796fb18e8afa02fac

2022-10-11 02:05 UTC, hiji commented on samples/batch/doma2-spring-batch/pom.xml
> +    <relativePath>../../pom.xml</relativePath>
IDE（Intellij IDEA）で警告が出ていたからです。公式Docを見ても省略仕様は見当たらなかったのと、他のプロジェクトは全てpom.xmlまで指定していたので、明記する方に振りました。

2022-10-11 02:06 UTC, hiji commented on samples/common/doma2/src/main/java/keel/User.java
> +@Entity(immutable = true)
既存実装のEntityはすべてイミュータブルにしていたようなので合わせる形にしていました。

2022-10-11 02:09 UTC, hiji commented on samples/pom.xml
>      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
差分が出なかったので削除しました。（このコマンド初めて知りました）

9973cb7391c9297449a0811b9ccdc70bb4bf921c

2022-10-11 02:26 UTC, hiji commented on samples/api/api-error-handling/pom.xml
対応しました。
また、プロジェクトによってはDoma用のプロパティがそもそも無かったりもしたので、DialectやNaming、Loggerは統一するように合わせて修正しました。

2ae13b321d39918dc2ec3b1a1ead524400ea05bc

2022-10-11 07:46 UTC, backpaper0 commented on samples/common/doma2/src/main/java/keel/User.java
> +@Entity(immutable = true)
`UsersDao`にもエンティティをミュータブルからイミュータブルにする場合の変更が入っているように見えますが、ここだけミュータブルなエンティティが使われていたということですか？

2022-10-11 08:02 UTC, hiji commented on samples/common/doma2/src/main/java/keel/User.java
> +@Entity(immutable = true)
`UserDao`は戻り値とクラス名の修正だと思いますので、`Doma2App`の修正のことでしょうか？
ここは元々 Doma-Gen 2 を使って自動生成していたプロジェクトなんですが、ドキュメントを見ても `immutable` を設定する項目が見当たらず、おそらくですが`immutable=true`を設定できなくて仕方なくここだけミュータブルにしていたのかなと考えました。（他のプロジェクトは全てイミュータブルだったので）

2022-10-11 08:04 UTC, backpaper0 approved these changes

2022-10-11 08:04 UTC, merged