ドキュメントの見直し（Webアプリ開発のノウハウ - 認可）
ti-spring/spring-crib-notes pull request #10
Opened 2022-10-27 03:28 UTC by hiji

## 概要

## レビュー依頼前のチェックリスト

- [x] 作業時間を記録していること
- [x] セルフレビュー済みであること
- [x] PRに適切なtarget branchを設定済みであること

ソースコード特有の項目

- [x] 理解しづらいコードはコメントで補足説明済みであること
- [x] `./mvn clean verify`を実行して結果が`BUILD SUCCESS`であること

## 動作確認方法

- [ ] 生成したドキュメントがブラウザで正常に表示されていること
- [ ] `mvn spring-boot:run`で機能が動作すること

## レビューアに確認して欲しいポイント

- ドキュメント
  - 全体的に言い回し等をすこし変更しました
  - `thymeleaf-extras-springsecurity`の名前が変わってますが、今後のメンテを考えて「例えば」みたいな書き方にしました
  - ロールの階層構造について言及されていなかったので追記しました
- サンプルコード
  - Spring Serucityのドキュメントを見ていると`RoleHierarchy`はBean定義しなくてもよさそうに見えたのでまとめました

## レビューアへの申し送り事項

(もしあれば書く)

## その他、気になること

(もしあれば書く)

---

## レビュー後、マージ前のチェックリスト（レビューア用のチェックリスト）

- [ ] レビュー時間を記録していること
- [ ] PRに適切なtarget branchを設定済みであること

---

| 作業分類             |時間(h)|
|------------------|---|
| 実装・執筆            |1.0|
| レビュー(backpaper0) |0|

2022-10-28 09:56 UTC, backpaper0 requested changes

2022-10-28 09:56 UTC, backpaper0 commented on doc/web/authorization/index.rst
> +この例ではデータベースで認証・認可情報を管理しているため、ユーザ情報を取得する際に権限情報を取得し、ユーザ情報に設定します。
> ユーザ情報を取得する際に権限情報を取得し、ユーザ情報に設定します。

細かいですが「権限情報**も**取得し、」の方が良いと思いました。

2022-10-28 09:56 UTC, backpaper0 commented on doc/web/authorization/index.rst
> +エントリポイントごとにアクセス可能な権限を設定します。
元から書かれている表現に対するコメントですが、「エントリポイント」という表現は馴染みがない（主観ですが）のと、[Spring Securityのドキュメント](https://docs.spring.io/spring-security/reference/servlet/authorization/authorize-http-requests.html)を見てもentry pointという表現は出てこないため「URLパターンごとにアクセス可能な〜」の方が良いと思いましたが、どうでしょうか？

2022-10-28 09:56 UTC, backpaper0 commented on samples/web/table-authentication/src/main/java/keel/tableauth/SecurityConfig.java
> -    public RoleHierarchy roleHierarchy() {
詳細に追ったわけではないんですが、以下のコードを見ていると`RoleHierarchy`はbean定義しておいた方が良さそうに思いました。

- https://github.com/spring-projects/spring-security/blob/5.7.4/config/src/main/java/org/springframework/security/config/annotation/web/builders/WebSecurity.java#L371
- https://github.com/spring-projects/spring-security/blob/5.7.4/config/src/main/java/org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.java#L165-L168

2022-10-31 07:52 UTC, hiji commented on doc/web/authorization/index.rst
> +この例ではデータベースで認証・認可情報を管理しているため、ユーザ情報を取得する際に権限情報を取得し、ユーザ情報に設定します。
たしかにそちらのほうがよいと思いましたので対応しました。

9de40947f3af9fe9c5a2b7cca863d6c4fbe3d919

2022-10-31 07:55 UTC, hiji commented on doc/web/authorization/index.rst
> +エントリポイントごとにアクセス可能な権限を設定します。
たしかにそちらの方がわかりやすいと思いましたので対応しました。
ドキュメントを見てみて他に一般名称的なのがないかも見てみましたが特に無さそうでしたので、「URLパターン」にしました。
あと、ドキュメントを見ていたときに「アクセスに必要な権限」という言い回しを見かけたので、ドキュメント上の「アクセス可能な権限」もそちらに変更しました。

af411e74c88f333a678b0df501270da55dc53c27

2022-10-31 08:31 UTC, hiji commented on samples/web/table-authentication/src/main/java/keel/tableauth/SecurityConfig.java
> -    public RoleHierarchy roleHierarchy() {
色々と確認していて、Bean定義以前に実装に問題あることがわかりました。

- 現在のページ構造ではロール階層が検証できておらず、階層が有効になっていなくても問題なく動いているように見えてしまう
- Spring Security 5.5 から`AccessDecisionManager`に代わる`AuthorizationManager`が導入されている
- `AuthorizationManager`ではロール階層に対応されていない
  - - [v5.8から入りそう](https://github.com/spring-projects/spring-security/pull/11309)
- 公式ドキュメントのサンプルコードを参考にすると`HttpSecurity#authorizeHttpRequests`メソッドを使うことになるが、それだと`AuthorizationManager`が使用される
- `HttpSecurity#authorizeRequests`メソッドを使えば従来の`AccessDecisionManager`を使う方式になる
  - `AccessDecisionManager`は将来的には非推奨になる模様

`ROLE_user`権限がなければ表示できないページを追加して検証できるようにした上で、一旦`HttpSecurity#authorizeRequests`を使って従来型の実装に戻したところ、ロール階層が機能しました。

233c00c68843c6ca4215400f0821b20dccb3e339

2022-11-04 05:44 UTC, hiji commented on samples/web/table-authentication/src/main/java/keel/tableauth/SecurityConfig.java
> -    public RoleHierarchy roleHierarchy() {
Tipsに`AccessDecisionManager`を使う場合の注意点について追記しました。

cdab2899d1e32d7d41fe0b150c534a6ee98f161f

2022-11-07 04:53 UTC, backpaper0 approved these changes

2022-11-07 04:53 UTC, merged