Rest error handling
ti-spring/spring-crib-notes pull request #11
Opened 2022-10-28 02:36 UTC by hiji

## 概要

## レビュー依頼前のチェックリスト

- [x] 作業時間を記録していること
- [x] セルフレビュー済みであること
- [x] PRに適切なtarget branchを設定済みであること

ソースコード特有の項目

- [x] 理解しづらいコードはコメントで補足説明済みであること
- [x] `./mvn clean verify`を実行して結果が`BUILD SUCCESS`であること

## 動作確認方法

- [x] 生成したドキュメントがブラウザで正常に表示されていること
- [x] `mvn spring-boot:run`で機能が動作すること

## レビューアに確認して欲しいポイント

- ドキュメント
  - 文章表現
- サンプルコード
  - JSON変換が失敗した場合のエラーレスポンスの形式は他のものと近しい形がいいと考えて変更しました
  - ネストしたクラスは極力使わない方がいいと考えて抽出しました

## レビューアへの申し送り事項

(もしあれば書く)

## その他、気になること

(もしあれば書く)

---

## レビュー後、マージ前のチェックリスト（レビューア用のチェックリスト）

- [ ] レビュー時間を記録していること
- [ ] PRに適切なtarget branchを設定済みであること

---

| 作業分類             |時間(h)|
|------------------|---|
| 実装・執筆            |3|
| レビュー(backpaper0) |0|

2022-10-31 23:54 UTC, backpaper0 requested changes

2022-10-31 23:54 UTC, backpaper0 commented on doc/api/error-handling/index.rst
> -  ただし、reason属性に指定した値は、MessageSourceを使用して解決されません。そのため、reason属性に指定した値がそのまま出力されます。
念の為の確認ですが、この文章を削除した理由は`reason`要素が`MessageSource`を使用して解決されるようになっているからですか？

2022-10-31 23:54 UTC, backpaper0 commented on doc/api/error-handling/index.rst
>    reason属性に指定した値は、\ :spring-framework-doc:`MessageSource <javadoc-api/org/springframework/context/MessageSource.html>`\ を使用して解決されるため、
> reason属性

元の記述に対するコメントですが、Java言語仕様を見ても「属性」という表現はなく「要素」が適切かと思います。

- https://docs.oracle.com/javase/specs/jls/se19/html/jls-9.html#jls-9.6.1

2022-10-31 23:54 UTC, backpaper0 commented on doc/api/error-handling/index.rst
>    reason属性に指定した値は、\ :spring-framework-doc:`MessageSource <javadoc-api/org/springframework/context/MessageSource.html>`\ を使用して解決されるため、
……と思ったけど`ResponseStatus`のJavadocに「the reason attribute」という表現がありますね。

このコメントは取り下げます。

2022-10-31 23:54 UTC, backpaper0 commented on samples/api/api-error-handling/src/main/java/keel/apierrorhandling/ApiError.java
> +public class ApiError implements Serializable {
相談です。
`Serializable`を実装する意味はなさそうに思いますがどうでしょうか？
可能なら`Serializable`を実装しないようにしたいです。

2022-10-31 23:54 UTC, backpaper0 commented on samples/api/api-error-handling/src/test/java/keel/apierrorhandling/controller/UsersControllerTest.java
> +                .andExpect(jsonPath("$.message").value("入力形式に誤りがあります。"));
単に疑問なのですが、これって修正前はテストが失敗していたんですかね？

2022-11-01 08:30 UTC, hiji commented on doc/api/error-handling/index.rst
> -  ただし、reason属性に指定した値は、MessageSourceを使用して解決されません。そのため、reason属性に指定した値がそのまま出力されます。
いえ、検証では`reason`値が使われていなかったからです。使われる指定の仕方もあるかもしれませんが、指定パターンがあるならややこしいしあまり使いそうにも思えなかったので、削除しました。

検証は↓でやりました。

1. `Users2Controller`のExceptionHandlerに`@ResponsStatus`を指定
```
@RestController
@RequestMapping("/users2")
public class Users2Controller {
...
    @ExceptionHandler(MethodArgumentNotValidException.class)
    @ResponseStatus(value = HttpStatus.UNAUTHORIZED, reason = "keel.api-error-handling.MethodArgumentNotValidException")
    public void methodArgumentNotValidExceptionHandler() {}
}
```
2. `application.properties`に、メッセージを出力するための`server.error.include-message=always`を追加
3. CLIから`age`に`160`を設定してBeanValidationでエラーになるようなPOSTリクエストを送信
4. 返ってきたエラーレスポンスを確認したところ、`reason`値じゃなく標準メッセージが返却された
```
HTTP/1.1 401 
Connection: keep-alive
Content-Type: application/json
Date: Tue, 01 Nov 2022 08:24:06 GMT
Keep-Alive: timeout=60
Transfer-Encoding: chunked

{
    "error": "Unauthorized",
    "message": "Validation failed for object='userForm'. Error count: 1",
    "path": "/users2",
    "status": 401,
    "timestamp": "2022-11-01T08:24:06.097+00:00"
}
```

2022-11-01 08:34 UTC, hiji commented on samples/api/api-error-handling/src/test/java/keel/apierrorhandling/controller/UsersControllerTest.java
> +                .andExpect(jsonPath("$.message").value("入力形式に誤りがあります。"));
いえ、修正前はJSON形式じゃなく、レスポンスボディに文字列がそのまま入っているようなレスポンスになっていました。

ハンドリングしないエラーレスポンスはSpring BootgがJSON形式で返却するのもあり、実際に使うときはレスポンスボディはJSON形式である程度合わせるだろうなと考えたので、JSONの`message`要素としてエラーメッセージを返却するように構造を変更しました。

ここのテストは、それに合わせて修正したものになります。

2022-11-01 08:41 UTC, hiji commented on samples/api/api-error-handling/src/main/java/keel/apierrorhandling/ApiError.java
> +public class ApiError implements Serializable {
元々のクラスを抽出したときに、そこに気づいていませんでした。仰る通り不要なので削除しました。

4e925caf90a6708653f3d6c48709656389778483

2022-11-02 00:23 UTC, backpaper0 approved these changes

2022-11-02 00:23 UTC, merged