バッチの起動方法のページを見直し
ti-spring/spring-crib-notes pull request #17
Opened 2022-11-04 12:24 UTC by hiji

## 概要

## レビュー依頼前のチェックリスト

- [x] 作業時間を記録していること
- [x] セルフレビュー済みであること
- [x] PRに適切なtarget branchを設定済みであること

ソースコード特有の項目

- [ ] 理解しづらいコードはコメントで補足説明済みであること
- [ ] `./mvn clean verify`を実行して結果が`BUILD SUCCESS`であること

## 動作確認方法

- [ ] 生成されたHTMLをブラウザで正常に表示できていることを確認

## レビューアに確認して欲しいポイント

- ドキュメント

## レビューアへの申し送り事項

(もしあれば書く)

## その他、気になること

(もしあれば書く)

---

## レビュー後、マージ前のチェックリスト（レビューア用のチェックリスト）

- [ ] レビュー時間を記録していること
- [ ] PRに適切なtarget branchを設定済みであること

---

| 作業分類             |時間(h)|
|------------------|---|
| 実装・執筆            |0|
| レビュー(backpaper0) |0|

2022-11-07 05:31 UTC, backpaper0 requested changes

2022-11-07 05:31 UTC, backpaper0 commented on doc/batch/run-application/index.rst
> +日付などに関係なく常に実行できるようにしたい場合には、ジョブの設定で ``RunIdIncrementer`` を指定します。
もとから`RunIdIncrementer`を使用しているわけですが、サンプルプロジェクトでは`RunIdIncrementer`が微妙だと判断し、[JsrJobParametersConverter](https://github.com/ti-spring/spring-sample-project/blob/develop/sourcecode/batch/src/main/java/com/example/batch/common/configuration/BatchConfig.java#L34-L42)を使用するようにしました。

`RunIdIncrementer`の何が微妙かというと、前回のジョブ実行時のパラメーターをコピーして`run.id`をインクリメントするところにあります。

例えば、前回のジョブ実行時のパラメーターが`{ "run.id": 1, "date": "2022-11-06" }`だとすると、何もパラメーターを渡さなくても`{ "run.id": 2, "date": "2022-11-06" }`というパラメーターでジョブ起動することになります。

上記の場合、常に`date`パラメーターを設定しているなら良いんですが、例えばデフォルトではパラメーターを渡さずアプリケーション実行時に内部でシステム日付を取得してそれを使うが、トラブル時のリカバリーなどではパラメーターとして日付を渡す、といった仕様のバッチがある場合、平常時の「デフォルトではパラメーターを渡さず」が実現できなくなります。

かといってサンプルプロジェクトで採用した`JsrJobParametersConverter`も微妙と言えば微妙で、その名の通りJSR由来のクラスなためSpring Batch 6.xでは削除されます。

以上のことから、どちらを選んでも微妙なんですが、Spring Batch 6.xやSpring Boot 3.xがリリースされてもすぐに使うことはないだろうという考えや`RunIdIncrementer`の微妙さを鑑みて、サンプルプロジェクトでは`JsrJobParametersConverter`を採用したという感じです。

こっちのノウハウ集からもできれば`RunIdIncrementer`は削除したいです。

2022-11-08 03:39 UTC, hiji commented on doc/batch/run-application/index.rst
> +日付などに関係なく常に実行できるようにしたい場合には、ジョブの設定で ``RunIdIncrementer`` を指定します。
`JsrJobParametersConverter`に対応しました。↑で書いていただいた注意点については使用者が理解しておく必要があると思いましたので、ドキュメントのTipsとして追記しました。

bc70baf0b7020e8033d50a63346ed1b3a7894b42

2022-11-08 05:27 UTC, backpaper0 commented on doc/batch/run-application/index.rst
> +日付などに関係なく常に実行できるようにしたい場合には、ジョブの設定で ``RunIdIncrementer`` を指定します。
> 起動時のパラメータが指定されていなければ前回実行時のパラメータが復元される仕様になっているため

これだと前回実行時のパラメータが`run.id=1, p1=foo, p2=bar`の場合、`p1=xxx`と指定すればパラメータは`run.id=2, p1=xxx`となるように読めますが、実際には`run.id=2, p1=xxx, p2=bar`です。

つまり、起動時にパラメータを指定しようがしまいが前回のパラメータを復元する、同名のパラメータがあれば上書きする、といった感じですね。

2022-11-08 08:50 UTC, hiji commented on doc/batch/run-application/index.rst
> +日付などに関係なく常に実行できるようにしたい場合には、ジョブの設定で ``RunIdIncrementer`` を指定します。
私の理解が誤っていたので、説明を修正しました。

fa2b4fb0c2805d29529d02fb05ab1a7604ba41f8

2022-11-08 09:03 UTC, backpaper0 approved these changes

2022-11-08 09:03 UTC, merged