ドキュメントの見直し（AWS利用のノウハウ - SESでメール送信）
ti-spring/spring-crib-notes pull request #21
Opened 2022-11-11 09:48 UTC by hiji

## 概要

## レビュー依頼前のチェックリスト

- [x] 作業時間を記録していること
- [x] セルフレビュー済みであること
- [x] PRに適切なtarget branchを設定済みであること

ソースコード特有の項目

- [x] 理解しづらいコードはコメントで補足説明済みであること
- [x] `./mvn clean verify`を実行して結果が`BUILD SUCCESS`であること

## 動作確認方法

- [x] 生成したドキュメントがブラウザで正常に表示されていること
- [x] `mvn spring-boot:run`で機能が動作すること

## レビューアに確認して欲しいポイント

- ローカルではLocalStackを使うように変更しました

## レビューアへの申し送り事項

Spring AWS Cloud 2.4 ではSES用に spring-cloud-starter-aws-ses が提供されていて、[リファレンス](https://docs.awspring.io/spring-cloud-aws/docs/2.4.2/reference/html/index.html#configuring-regions)でも少しだけ触れられています。ただ、これを使うとエンドポイントをプロパティで設定できなくなるため、これは使わずに旧来の依存関係にしています。
（`AmazonWebserviceClientFactoryBean` でエンドポイントを設定したclientが生成されているので、そのあたりのBean定義をカスタムすればいけるようにも思うのですが、複雑になりそうなのでやめました）

## その他、気になること

(もしあれば書く)

---

## レビュー後、マージ前のチェックリスト（レビューア用のチェックリスト）

- [ ] レビュー時間を記録していること
- [ ] PRに適切なtarget branchを設定済みであること

---

| 作業分類             |時間(h)|
|------------------|---|
| 実装・執筆            |7.0|
| レビュー(backpaper0) |0|

2022-11-14 08:50 UTC, backpaper0 requested changes

2022-11-14 08:50 UTC, backpaper0 commented on doc/aws/ses/index.rst
> +この例では、メールアドレスが環境によって異なる場合を想定し、プロパティファイルで設定可能にする実装とします。
細かいですが「プロパティで設定可能にする〜」の方が良いと思います。
プロパティはファイル以外の方法でも設定可能ですので。

2022-11-14 08:50 UTC, backpaper0 commented on samples/aws/ses/pom.xml
> -      <artifactId>spring-boot-configuration-processor</artifactId>
これはなぜ削除するのでしょうか？
独自のプロパティを定義するなら`spring-boot-configuration-processor`を追加しておいた方が良いと思っています。

2022-11-14 08:50 UTC, backpaper0 commented on doc/aws/ses/index.rst
> +ファイルを添付する場合は、Spring Bootが提供する ``JavaMailSender`` を使用して実装できます。
Spring BootではなくSpring Frameworkが提供していませんか？

2022-11-14 08:50 UTC, backpaper0 commented on samples/aws/ses/README.md
> +mvn spring-boot:run -Dspring-boot.run.arguments=<アップロード対象のファイルパス> -Dspring-boot.run.profiles=<プロファイル>
`<アップロード対象のファイルパス>`は不要ですね。

2022-11-14 08:50 UTC, backpaper0 commented on samples/aws/ses/pom.xml
>    </dependencies>
サンプルコードの実行ログを見ると次のような警告が出ていました。

```
2022-11-14 17:46:44.099  WARN 61537 --- [           main] com.amazonaws.util.Base64                : JAXB is unavailable. Will fallback to SDK implementation which may be less performant.If you are using Java 9+, you will need to include javax.xml.bind:jaxb-api as a dependency. 
```

JAXB関係の依存も追加しておいた方が良いように思いました。

2022-11-15 02:40 UTC, hiji commented on samples/aws/ses/pom.xml
>    </dependencies>
すみません、気づいていませんでした。依存関係を追加しました。
5cef6887ddc070b4ff791b30894e4f330dcfb1f4

2022-11-15 02:41 UTC, hiji commented on samples/aws/ses/README.md
> +mvn spring-boot:run -Dspring-boot.run.arguments=<アップロード対象のファイルパス> -Dspring-boot.run.profiles=<プロファイル>
コピペミスでしたので修正しました。
e5b2493cd6a382fb5f33a7b67542f67e56a32aaa

2022-11-15 02:41 UTC, hiji commented on doc/aws/ses/index.rst
> +ファイルを添付する場合は、Spring Bootが提供する ``JavaMailSender`` を使用して実装できます。
おっしゃるとおりですので修正しました。他の箇所ではSpring Framework提供の場合は「Springが提供する〜」と書いていたのでそれに合わせています。
be3012d0c7356bc928f65d2d764ab6d7e0467d60

2022-11-15 02:42 UTC, hiji commented on doc/aws/ses/index.rst
> +この例では、メールアドレスが環境によって異なる場合を想定し、プロパティファイルで設定可能にする実装とします。
おっしゃるとおりですので、「ファイル」記述を除去しました。
ed61de0488a60127dca39eae727d7027a4c792cf

2022-11-15 02:43 UTC, hiji commented on samples/aws/ses/pom.xml
> -      <artifactId>spring-boot-configuration-processor</artifactId>
勘違いしており、この依存関係を理解できておりませんでした。確認したところおっしゃる通り追加するべきだと思いましたので追加しました。
ed61de0488a60127dca39eae727d7027a4c792cf

2022-11-15 04:03 UTC, backpaper0 approved these changes

2022-11-15 04:46 UTC, merged