Mybatis
ti-spring/spring-crib-notes pull request #22
Opened 2022-11-14 05:32 UTC by hiji

## 概要

## レビュー依頼前のチェックリスト

- [x] 作業時間を記録していること
- [x] セルフレビュー済みであること
- [x] PRに適切なtarget branchを設定済みであること

ソースコード特有の項目

- [x] 理解しづらいコードはコメントで補足説明済みであること
- [x] `./mvn clean verify`を実行して結果が`BUILD SUCCESS`であること

## 動作確認方法

- [x] 生成したドキュメントがブラウザで正常に表示されていること
- [x] `mvn spring-boot:run`で機能が動作すること

## レビューアに確認して欲しいポイント

- ドキュメントにどこまで書くかを少し悩みましたが、Doma2のページと同レベルのものまでとしました
- サンプルコードはDoma2をベースに作成しましたが、SELECTはあった方がいいかなと思ったので追加しました。

## レビューアへの申し送り事項

(もしあれば書く)

## その他、気になること

(もしあれば書く)

---

## レビュー後、マージ前のチェックリスト（レビューア用のチェックリスト）

- [ ] レビュー時間を記録していること
- [ ] PRに適切なtarget branchを設定済みであること

---

| 作業分類             |時間(h)|
|------------------|---|
| 実装・執筆            |4.0|
| レビュー(backpaper0) |0|

2022-11-14 09:10 UTC, backpaper0 requested changes

2022-11-14 09:10 UTC, backpaper0 commented on samples/common/mybatis/README.md
> +データベースの情報からDoma2用Entityが自動生成されアプリケーションが実行されます。
Doma2ではないし、Entityも自動生成されないですね。

2022-11-14 09:10 UTC, backpaper0 commented on samples/common/mybatis/README.md
> +データベースの情報からDoma2用Entityが自動生成されアプリケーションが実行されます。
あと、Doma2の方の`README.md`も「自動生成され」と書かれているのでついでに修正をお願いします（見落としていました、、、すみません）。

2022-11-14 09:10 UTC, backpaper0 commented on samples/common/mybatis/pom.xml
> +            <artifactId>doma-spring-boot-starter</artifactId>
`doma-spring-boot-starter`は削除してください。

2022-11-14 09:10 UTC, backpaper0 commented on samples/common/mybatis/pom.xml
> +            <artifactId>h2</artifactId>
H2のAPIを直接使うわけではないため`runtime`スコープで良いと思います（Spring Initializrを使ってプロジェクトを生成しても`runtime`スコープになります）。

2022-11-14 09:10 UTC, backpaper0 commented on samples/common/mybatis/pom.xml
> +            <artifactId>h2</artifactId>
Doma2のサンプルも同様でした。ついでに修正をお願いします。

2022-11-14 09:10 UTC, backpaper0 commented on samples/common/mybatis/src/main/resources/application.properties
> +spring.datasource.password=password
Doma2のサンプルも同じなんですが、インメモリH2を使うにあたってわざわざ`username`と`password`だけを定義する意味は薄いような……？

削除してしまいたいです。

2022-11-14 11:32 UTC, hiji commented on samples/common/mybatis/src/main/resources/application.properties
> +spring.datasource.password=password
おっしゃる通りですので、削除しました。
cb962251e2c2b0b75e8d8d828148fb8db6277449

2022-11-14 11:32 UTC, hiji commented on samples/common/mybatis/pom.xml
> +            <artifactId>h2</artifactId>
気づいていませんでしたので、修正しました。

3c6f0bb6f8653aabb39df93316eb106919f63e0a

2022-11-14 11:33 UTC, hiji commented on samples/common/mybatis/pom.xml
> +            <artifactId>doma-spring-boot-starter</artifactId>
すみません、削除が漏れていました。修正しました。
af371e1d73af74f8cc070cfcbc12ed6a60191e8a

2022-11-14 11:33 UTC, hiji commented on samples/common/mybatis/README.md
> +データベースの情報からDoma2用Entityが自動生成されアプリケーションが実行されます。
すみません、削除が漏れていました。修正しました。
eac365b9878be331e5bc5ecc68efca2c95657b0a
634428811f3d7d37b490b93904cd44188b2c27ec

2022-11-15 02:53 UTC, backpaper0 commented on samples/common/mybatis/pom.xml
> +            <artifactId>h2</artifactId>
`git grep -A 3 com.h2database`してみたところ、以下のプロジェクトも`compile`スコープのようでした。

- `samples/api/api-error-handling/pom.xml`
- `samples/common/sql-management/pom.xml`
- `samples/web/double-submission/pom.xml`
- `samples/web/error-handling/pom.xml`
- `samples/web/table-authentication/pom.xml`
- `samples/web/validation/pom.xml`

ちょっと多いですが、これらも修正してもらっていいですか？

2022-11-15 02:57 UTC, backpaper0 commented on samples/common/mybatis/src/main/resources/application.properties
> +spring.datasource.password=password
以下のファイルも対象ですね。対応をお願いしたいです。

- `samples/api/api-error-handling/src/main/resources/application.properties`
- `samples/web/double-submission/src/main/resources/application.properties`

2022-11-15 12:43 UTC, hiji commented on samples/common/mybatis/src/main/resources/application.properties
> +spring.datasource.password=password
他のプロジェクトで同様の箇所も確認し、プロパティを削除しました。

2e506f990b74d8361b29635fa8b06d6360d8cea1

2022-11-15 12:44 UTC, hiji commented on samples/common/mybatis/pom.xml
> +            <artifactId>h2</artifactId>
他プロジェクトでも同じ箇所を確認し、修正しました。Teamsでお伝えしたとおり、`samples/common/sql-management/pom.xml`についてはPlugin内の依存のため対象外にしています。

6ad47a356a4ff24d83d0718fb42ffa756c2088ca

2022-11-15 12:47 UTC, hiji commented on samples/common/mybatis/src/main/resources/application.properties
> +spring.datasource.password=password
プロパティを確認していた際、バッチのDoma2サンプルにコメントアウトされたプロパティを見つけたため、合わせて削除しました。多重起動の検証用にPostgreSQLに切り替える設定を残していると思われるのですが、あくまでドキュメント作成者向けで利用者には特に説明もしていないので、サンプルコードとしては不要と判断しました。

d1b07748af90ae46d9e1775d1deb65c4ad5c8b53

2022-11-16 02:33 UTC, backpaper0 approved these changes

2022-11-16 02:33 UTC, merged