ドキュメント追加（Nablarch使用ノウハウ - ドメインバリデーション）
ti-spring/spring-crib-notes pull request #28
Opened 2022-11-21 11:11 UTC by hiji

## 概要

## レビュー依頼前のチェックリスト

- [x] 作業時間を記録していること
- [x] セルフレビュー済みであること
- [x] PRに適切なtarget branchを設定済みであること

ソースコード特有の項目

- [x] 理解しづらいコードはコメントで補足説明済みであること
- [x] `./mvn clean verify`を実行して結果が`BUILD SUCCESS`であること

## 動作確認方法

- [x] 生成したドキュメントがブラウザで正常に表示されていること
- [x] `mvn spring-boot:run`で機能が動作すること

## レビューアに確認して欲しいポイント

- コード参照が多すぎて見づらい感じもしますが、記載しないのもどうかと思ったのでそのまま載せています
- コード管理と日付管理を合わせて1プロジェクトとする話をしましたが、まとめると少し説明しづらそうにも思えたので分けました

## レビューアへの申し送り事項

(もしあれば書く)

## その他、気になること

(もしあれば書く)

---

## レビュー後、マージ前のチェックリスト（レビューア用のチェックリスト）

- [ ] レビュー時間を記録していること
- [ ] PRに適切なtarget branchを設定済みであること

---

| 作業分類             |時間(h)|
|------------------|---|
| 実装・執筆            |8.0|
| レビュー(backpaper0) |0|

2022-11-24 11:28 UTC, backpaper0 requested changes

2022-11-24 11:28 UTC, backpaper0 commented on doc/nablarch/validation/index.rst
> +  .. literalinclude:: ../../../samples/nablarch/nablarch-validation/src/main/java/keel/nablarch/validation/CharsetDefProperties.java
提案ですが、ちょっと縦に長すぎるので、アクセサはインクルードせず「アクセサは省略する」みたいな補足をいれておいても良いと思いました。

2022-11-24 11:28 UTC, backpaper0 commented on doc/nablarch/validation/index.rst
> +Nablarchが提供するバリデーターでは、メッセージを定義するためプロパティ名がデフォルトで設定されているため、使用するバリデーターに合わせてメッセージを定義します。
デフォルトの「プロパティ名」が設定されるだけであって、デフォルトの「メッセージ」は設定されないですよね？

なんとなくデフォルトのメッセージが設定されるように読める気がしました。

2022-11-24 11:28 UTC, backpaper0 commented on doc/nablarch/validation/index.rst
> +デフォルトのプロパティ名はアノテーション指定時に上書きすることができるため、独自のプロパティについても定義します。
この一文はなくてもいいと思いました。

あまりプロパティ名を上書きすることはないんじゃないかと思ったのと、後に出てくる`messages.properties`の例で特に独自のプロパティを定義していないため不要だと思いました。

2022-11-24 11:28 UTC, backpaper0 commented on samples/nablarch/nablarch-validation/src/main/resources/messages.properties
> +nablarch.core.validation.ee.Digits.integer.message=数値を入力してください。
数値項目に`a`などを入力された場合と、下限・上限のエラーになった場合を考慮し、次のメッセージは定義しておいた方が良いと思いました。

```
nablarch.core.validation.ee.NumberRange.min.max.message={min}以上{max}以下の数値を入力してください。
typeMismatch.java.lang.Integer=数値を入力してください。
```

2022-11-25 08:48 UTC, hiji commented on samples/nablarch/nablarch-validation/src/main/resources/messages.properties
> +nablarch.core.validation.ee.Digits.integer.message=数値を入力してください。
定義が漏れていたため、定義を追加しました。

6e4ed2e820fab0e28be9974655c8fed79ce82698

2022-11-25 08:49 UTC, hiji commented on doc/nablarch/validation/index.rst
> +デフォルトのプロパティ名はアノテーション指定時に上書きすることができるため、独自のプロパティについても定義します。
ドメインBeanで独自のメッセージプロパティは定義していますが、あえて変更する必要性はないため、標準のプロパティ名に修正しました。

6e4ed2e820fab0e28be9974655c8fed79ce82698

2022-11-25 08:50 UTC, hiji commented on doc/nablarch/validation/index.rst
> +  .. literalinclude:: ../../../samples/nablarch/nablarch-validation/src/main/java/keel/nablarch/validation/CharsetDefProperties.java
ページを全体的に見直し、コードの参照範囲も狭くなるように見直しました。

7abaa4b614a3ff430d082f0bcda4e6992f62ba41

2022-11-25 08:51 UTC, hiji commented on doc/nablarch/validation/index.rst
> +Nablarchが提供するバリデーターでは、メッセージを定義するためプロパティ名がデフォルトで設定されているため、使用するバリデーターに合わせてメッセージを定義します。
ページを全体的に見直し、該当箇所の文章も見直しました。

7abaa4b614a3ff430d082f0bcda4e6992f62ba41

2022-11-28 01:57 UTC, backpaper0 approved these changes

2022-11-28 01:57 UTC, merged