ドキュメント追加（Nablarch使用ノウハウ - コード管理）
ti-spring/spring-crib-notes pull request #29
Opened 2022-11-24 12:30 UTC by hiji

## 概要

## レビュー依頼前のチェックリスト

- [x] 作業時間を記録していること
- [x] セルフレビュー済みであること
- [x] PRに適切なtarget branchを設定済みであること

ソースコード特有の項目

- [x] 理解しづらいコードはコメントで補足説明済みであること
- [x] `./mvn clean verify`を実行して結果が`BUILD SUCCESS`であること

## 動作確認方法

- [x] 生成したドキュメントがブラウザで正常に表示されていること
- [x] `mvn spring-boot:run`で機能が動作すること

## レビューアに確認して欲しいポイント

全般

## レビューアへの申し送り事項

ドメインバリデーションとは参照の範囲を変えて、Bean定義の部分だけなど参照範囲を狭くしてみました。
こちらの方が見やすそうであれば、ドメインバリデーションも合わせようと思います。

## その他、気になること

(もしあれば書く)

---

## レビュー後、マージ前のチェックリスト（レビューア用のチェックリスト）

- [ ] レビュー時間を記録していること
- [ ] PRに適切なtarget branchを設定済みであること

---

| 作業分類             |時間(h)|
|------------------|---|
| 実装・執筆            |7.0|
| レビュー(backpaper0) |0|

2022-11-25 02:57 UTC, backpaper0 requested changes

2022-11-25 02:57 UTC, backpaper0 commented on samples/nablarch/nablarch-code/src/main/java/keel/nablarch/validation/ValidationConfiguration.java
> +import org.springframework.boot.context.properties.ConfigurationProperties;
不要な`import`です。

2022-11-25 02:57 UTC, backpaper0 commented on samples/nablarch/nablarch-code/src/main/java/keel/nablarch/validation/ValidationConfiguration.java
> +import org.springframework.context.annotation.PropertySource;
こちらも不要な`import`です。

2022-11-25 02:57 UTC, backpaper0 commented on samples/nablarch/nablarch-code/pom.xml
> +
独自のプロパティを定義しているため`spring-boot-configuration-processor`を追加しておいてもらいたいです。

```
    <dependency>
    	<groupId>org.springframework.boot</groupId>
    	<artifactId>spring-boot-configuration-processor</artifactId>
    	<optional>true</optional>
    </dependency>
```

2022-11-25 09:01 UTC, hiji commented on samples/nablarch/nablarch-code/src/main/java/keel/nablarch/validation/ValidationConfiguration.java
> +import org.springframework.boot.context.properties.ConfigurationProperties;
対応しました。

90c2e99ee26b8963ee342eb6b608fa58a7c0bd25

2022-11-25 09:01 UTC, hiji commented on samples/nablarch/nablarch-code/src/main/java/keel/nablarch/validation/ValidationConfiguration.java
> +import org.springframework.context.annotation.PropertySource;
対応しました。

90c2e99ee26b8963ee342eb6b608fa58a7c0bd25

2022-11-25 09:03 UTC, hiji commented on samples/nablarch/nablarch-code/pom.xml
> +
Teamsでお伝えしましたとおり、依存を追加したのですがnablarchのプロパティ用のメタデータがうまく生成されませんでした。調査に時間がかかりそうなため、対応は一旦無しとさせてください。

2022-11-25 09:05 UTC, hiji commented
太字になっていない箇所のスタイルを調整しました。
e7c9b46f031733917b74f03ddd9666f532fd70ef

また、ドメインバリデーションのページに合わせて、一部の表記を見直しました。
fe5939e38b5420e918c18cde98196cf6377085b6

2022-11-28 02:38 UTC, backpaper0 requested changes

2022-11-28 02:38 UTC, backpaper0 commented on doc/nablarch/code/index.rst
> +  .. literalinclude:: ../../../samples/nablarch/nablarch-validation/pom.xml
include元が間違っていますね。

2022-11-28 02:38 UTC, backpaper0 commented on doc/nablarch/code/index.rst
> +コード情報にアクセスする際に使用する :nablarch-doc:`BasicCodeManager <javadoc/nablarch/common/code/BasicCodeManager.html>`` をBean定義します。
ビルドしたドキュメントを見るとリンクがおかしくなっていました。
後ろのバッククォートが1つ多い？

2022-11-28 02:38 UTC, backpaper0 commented on doc/nablarch/code/index.rst
> +ドメインバリデーションを動作させるための設定については、 :ref:`Nablarchのドメインバリデーションを使用して入力値をチェックする <nablarch-validation>` を参照してください。
リンクになっていませんでした。

ビルド時に以下の警告が出ているので、これが原因かと。

> /repos/doc/nablarch/code/index.rst:121: WARNING: undefined label: 'nablarch-validation'

2022-11-28 02:38 UTC, backpaper0 commented on doc/nablarch/code/index.rst
> +ドメインバリデーションを動作させるための設定については、 :ref:`Nablarchのドメインバリデーションを使用して入力値をチェックする <nablarch-validation>` を参照してください。
`git rebase master`したら正しいリンクになりました。

2022-11-28 04:50 UTC, hiji commented on doc/nablarch/code/index.rst
> +  .. literalinclude:: ../../../samples/nablarch/nablarch-validation/pom.xml
修正しました。

d72cce57fc509779dd26d276ef2a30ef45e4ce79

2022-11-28 04:51 UTC, hiji commented on doc/nablarch/code/index.rst
> +コード情報にアクセスする際に使用する :nablarch-doc:`BasicCodeManager <javadoc/nablarch/common/code/BasicCodeManager.html>`` をBean定義します。
修正しました。

12f704097911b58092677b9993de70d9d15e91b4

2022-11-28 04:52 UTC, hiji commented on doc/nablarch/code/index.rst
> +ドメインバリデーションを動作させるための設定については、 :ref:`Nablarchのドメインバリデーションを使用して入力値をチェックする <nablarch-validation>` を参照してください。
こちらはドメインバリデーションがマージされた後の前提で書いていました。伝え漏れてしまい、すみません。

2022-11-28 04:52 UTC, hiji commented on doc/nablarch/code/index.rst
> +ドメインバリデーションを動作させるための設定については、 :ref:`Nablarchのドメインバリデーションを使用して入力値をチェックする <nablarch-validation>` を参照してください。
他にも警告が発生していたので、対応しました。

82c8b6eca78fcb2187bd34b457a9b782e2a8cff2
e62ba7969bfcc9132678347e529d7fc2667966f2

2022-11-28 07:00 UTC, backpaper0 approved these changes

2022-11-28 07:00 UTC, merged