ドキュメントの見直し（Webアプリ開発のノウハウ - 例外ハンドリング）
ti-spring/spring-crib-notes pull request #3
Opened 2022-10-07 06:28 UTC by hiji

## 概要

## レビュー依頼前のチェックリスト

- [x] 作業時間を記録していること
- [x] セルフレビュー済みであること
- [x] PRに適切なtarget branchを設定済みであること

ソースコード特有の項目

- [ ] 理解しづらいコードはコメントで補足説明済みであること
- [ ] `./mvn clean verify`を実行して結果が`BUILD SUCCESS`であること

## 動作確認方法

- [x] 生成したHTMLの表示が崩れていないこと

## レビューアに確認して欲しいポイント

- ドキュメントの修正内容
  - デフォルトエラー画面について説明がなかったので追加しました
  - サンプルコードにある任意のエラーページ名を返す方法がドキュメントで触れていなかかったので追加しました

## レビューアへの申し送り事項

(もしあれば書く)

## その他、気になること

(もしあれば書く)

---

## レビュー後、マージ前のチェックリスト（レビューア用のチェックリスト）

- [ ] レビュー時間を記録していること
- [ ] PRに適切なtarget branchを設定済みであること

---

| 作業分類             |時間(h)|
|------------------|---|
| 実装・執筆            |4|
| レビュー(backpaper0) |0|

2022-10-11 09:22 UTC, backpaper0 requested changes

2022-10-11 09:22 UTC, backpaper0 commented on doc/web/error-handling/index.rst
> +エラーが返却された場合、 デフォルトで :spring-boot-doc:`Sping Bootが提供しているエラー画面が表示されます <reference/htmlsingle/#web.servlet.spring-mvc.error-handling>` 。エラー画面の動作については ``server.error`` プロパティでカスマイズすることができます。プロパティの詳細については :
`htmlsingle`へのリンクになっています。

2022-10-12 05:20 UTC, hiji commented on doc/web/error-handling/index.rst
> +エラーが返却された場合、 デフォルトで :spring-boot-doc:`Sping Bootが提供しているエラー画面が表示されます <reference/htmlsingle/#web.servlet.spring-mvc.error-handling>` 。エラー画面の動作については ``server.error`` プロパティでカスマイズすることができます。プロパティの詳細については :
すみません、修正しました。

0a49cab4578e7f88edf23bb028530d4911cb1224

2022-10-12 05:28 UTC, backpaper0 approved these changes

2022-10-12 05:28 UTC, merged