ドキュメントの見直し（Webアプリ開発のノウハウ - ファイルダウンロード）
ti-spring/spring-crib-notes pull request #5
Opened 2022-10-12 07:34 UTC by hiji

## 概要

## レビュー依頼前のチェックリスト

- [ ] 作業時間を記録していること
- [ ] セルフレビュー済みであること
- [ ] PRに適切なtarget branchを設定済みであること

ソースコード特有の項目

- [ ] 理解しづらいコードはコメントで補足説明済みであること
- [ ] `./mvn clean verify`を実行して結果が`BUILD SUCCESS`であること

## 動作確認方法

- [ ] ...
- [ ] ...

## レビューアに確認して欲しいポイント

## レビューアへの申し送り事項

(もしあれば書く)

## その他、気になること

(もしあれば書く)

---

## レビュー後、マージ前のチェックリスト（レビューア用のチェックリスト）

- [ ] レビュー時間を記録していること
- [ ] PRに適切なtarget branchを設定済みであること

---

| 作業分類             |時間(h)|
|------------------|---|
| 実装・執筆            |0|
| レビュー(backpaper0) |0|

2022-10-13 06:51 UTC, backpaper0 requested changes

2022-10-13 06:51 UTC, backpaper0 commented on samples/web/file-download/src/main/java/keel/filedownload/TextFileDownloadView.java
>          response.setHeader("Content-Disposition", "attachment; filename=" + attributes.getDownloadFileName());
元からある部分ですが、`filename*`ディレクティブを使用するようにしたいです。

- https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/Content-Disposition#filename_2

2022-10-26 00:17 UTC, hiji commented on samples/web/file-download/src/main/java/keel/filedownload/TextFileDownloadView.java
>          response.setHeader("Content-Disposition", "attachment; filename=" + attributes.getDownloadFileName());
`filename*`ディレクティブを使用するように変更しました。ファイル名も日本語にして文字コード指定するようにしています。

その動作確認中に気づいたのですが、`spring-boot:run`で起動するとダウンロードが正常に動作していなかったため、合わせて修正しました。

9cdef3db50c85972a9236156739742523240de76

2022-10-26 08:27 UTC, backpaper0 requested changes

2022-10-26 08:27 UTC, backpaper0 commented on samples/web/file-download/src/main/java/keel/filedownload/UserController.java
> +                new FileDownloadAttributes(targetFilePath, "テスト.txt"));
めっちゃ細かいし、どちらでも良いと言えば良いんですが、「サンプル.txt」または「ダウンロード.txt」にしたい気がしました。

2022-10-26 10:19 UTC, hiji commented on samples/web/file-download/src/main/java/keel/filedownload/UserController.java
> +                new FileDownloadAttributes(targetFilePath, "テスト.txt"));
たしかに言われてみればそちらの方がよいと思いました。
元々は`download.txt`だったので、`ダウンロード.txt`にします。

dbd3fac49a20e1be26cfafc89a9deeeafc26fc83

2022-10-26 21:38 UTC, backpaper0 approved these changes

2022-10-27 00:15 UTC, merged